### PR TITLE
Implements listAll operation for VirtualNetworkAPI

### PR DESCRIPTION
**Pull request by danielestevez**
This should be the last of these improvements.

Again jclouds doesn't use the method

### CODE REVIEW

**Comment by nacx** [comment]
LGTM but tests need to be fixed

**Comment by danielestevez** [comment]
sorry, dumb mistake there

**Comment by danielestevez** [comment]
Found a bug in method signature. resourcegroup param should be nullable. Fixing....

**Comment by danielestevez** [comment]
And ready now!

**Pull request merged**
