### PR TITLE
Adding access key auth support for openstack V3

### PR DESCRIPTION
**Pull request by edipdemirbilek**
There was already [a PR](https://github.com/apache/jclouds/pull/142) for adding access key auth support for openstack V3. But it was declined due to lack of tests.

We run into the same problem. I have tried that earlier PR and it really fixes the problem. So I have added test cases to the initial PR as is and submitting them all together in this PR.

### CODE REVIEW

**Comment by edipdemirbilek** [comment]
Needs reviewer: @nacx @gaul

**Comment by nacx** [comment]
Thanks @edipdemirbilek! Could you fix the checkstyle violation to have the build green? The PR LGTM. I'll merge it once the build passes.
Thank you!

**Comment by edipdemirbilek** [comment]
> Thanks @edipdemirbilek! Could you fix the checkstyle violation to have the build green? The PR LGTM. I'll merge it once the build passes. Thank you!

done.

**Comment by edipdemirbilek** [comment]
@nacx build is still failing but not due to keystone project anymore as far as I see. Another sub-project (google-cloud-storage) is failing and this seems to have been the case for 2 months.

**Comment by nacx** [comment]
Fixes that in another PR.
Thank you!

**Comment by edipdemirbilek** [comment]
@nacx thank you. are you planning a new release anytime soon? what version of jclouds should we depend on?

**Comment by nacx** [comment]
Actually, we are discussing moving jclouds to the Attic, due to the lack of maintainers and active people in the project. @gaul wanted to do a final release before that happens, but as far as I know there is no deadline for that.

**Pull request merged**
