### PR TITLE
JCLOUDS-1496: Update maven-compiler-plugin for increased JDK compatibility

### PR DESCRIPTION
**Pull request by oflebbe**

### CODE REVIEW

**Comment by oflebbe** [comment]
The patch looks suspicious ... but I checked twice: I moved the maven-compiler-plugin block to the first <pluginManagement> plugin .

**Comment by oflebbe** [comment]
Errr ... I am failing to see the actual error in Jenkins

**Comment by gaul** [comment]
[This suggests](https://builds.apache.org/job/jclouds-pull-request-jobs/job/jclouds-pull-requests/103/console) Checkstyle violations:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check (default) on project jclouds-core: You have 10 Checkstyle violations. -> [Help 1]

Perhaps Checkstyle version was implicitly upgraded?

**Comment by oflebbe** [comment]
Cannot reproduce this errors. Or the other way around: The jenkins profile used by the CI does not work for me at all, since I do not use jdk 1.7 any more.

Seems to be related to the maven-toolchains plugin and configuration. Have to investigate.

**Comment by oflebbe** [comment]
I created a checkstyle-suppressions.xml file for ignoring generated files . OMG !

 maven-checkstyle-plugin is downloading the DTD from checkstyle.org (!) 
And it chokes on the TLS version 1.2  deployed there
`openssl s_client -host checkstyle.org -port 443 ` 

`
....
SSL-Session:
    Protocol  : TLSv1.2
 `

For JDK 1.7 on Mac I relied on the oracle download which is 1.7.0_80 , since newer are for Oracle customers only. TLS v1.2 is only supported starting  1.7.0_131 .

https://stackoverflow.com/questions/39157422/how-to-enable-tls-1-2-in-java-7

OMG !

**Comment by oflebbe** [comment]
Error message from maven-checkstyle-plugin

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (default) on project jclouds-project: Failed during checkstyle execution: Failed to load suppressions file from: /Users/olaf/Devel/jclouds/project/target/checkstyle-suppressions.xml: Unable to read /Users/olaf/Devel/jclouds/project/target/checkstyle-suppressions.xml: Received fatal alert: protocol_version -> [Help 1]
`

**Comment by oflebbe** [comment]
Ah oh, the old checkstyle plugin does only support an outdated DTD . Changing to old DTD now.

**Comment by oflebbe** [comment]
checkstyle should be resolved now

**Comment by oflebbe** [comment]
yes. I try to head even further to jdk11. I know we need updated maven for this, that the reason i am doing this :)

so next step is to increase maven compiler plugin version

**Comment by oflebbe** [comment]
This failure seems unrelated to my commit .

**Comment by oflebbe** [comment]
WHat did I do ? I somehow closed the pull

**Pull request merged**
